name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - main
  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Start Flask server in the background
      - name: Start Flask Server
        run: |
          nohup python path/to/your/app.py &

      # Wait for the server to start
      - name: Wait for Flask Server
        run: sleep 10  # Adjust this if necessary

      - name: Run Unit Tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Lint Code
        run: flake8 .

      # Deploy to Vercel based on the branch
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/dev'
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/staging'
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
