name: CI/CD Pipeline

# Trigger on push or pull request
on:
  push:
    branches:
      - dev         # Trigger for development environment
      - staging     # Trigger for staging environment
      - main        # Trigger for production environment
  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'  # Use the appropriate Python version

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      # Run unit tests
      - name: Run Unit Tests
        run: pytest

      # Lint the code
      - name: Lint Code
        run: flake8 .

      # Deploy to Vercel for development (if pushing to the dev branch)
      - name: Deploy to Vercel (Development)
        if: github.ref == 'refs/heads/dev'
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod

      # Deploy to Vercel for staging (if pushing to the staging branch)
      - name: Deploy to Vercel (Staging)
        if: github.ref == 'refs/heads/staging'
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod

      # Deploy to Vercel for production (if pushing to the main branch)
      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main'
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
